import type { App } from "vue";
import "element-plus/lib/theme-chalk/base.css";
import {
  ElAside,
  ElButton,
  ElCol,
  ElContainer,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  ElForm,
  ElFormItem,
  ElCheckbox,
  ElHeader,
  ElInput,
  ElSubmenu,
  ElTabPane,
  ElTabs,
  ElLink,
  ElMain,
  ElMenu,
  ElMenuItem,
  ElRow,
  ElSelect,
  ElDatePicker,
  ElOption,
  ElBreadcrumbItem,
  ElPagination,
  ElBreadcrumb,
  ElTable,
  ElTableColumn,
  ElImage,
  ElCard,
  ElDialog,
  ElCollapse,
  ElTree,
  ElAvatar,
  ElUpload,
  ElTooltip,
  ElDescriptionsItem,
  ElTag,
  ElCollapseItem,
  ElDescriptions
} from "element-plus";
const components = [
  ElAside,
  ElButton,
  ElCol,
  ElContainer,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  ElForm,
  ElFormItem,
  ElCheckbox,
  ElHeader,
  ElInput,
  ElSubmenu,
  ElTabPane,
  ElTabs,
  ElLink,
  ElMain,
  ElMenu,
  ElMenuItem,
  ElRow,
  ElSelect,
  ElDatePicker,
  ElOption,
  ElBreadcrumbItem,
  ElPagination,
  ElBreadcrumb,
  ElTable,
  ElTableColumn,
  ElImage,
  ElCard,
  ElDialog,
  ElCollapse,
  ElTree,
  ElAvatar,
  ElUpload,
  ElTooltip,
  ElDescriptionsItem,
  ElTag,
  ElCollapseItem,
  ElDescriptions
];

export default function (app: App): void {
  for (const cpn of components) {
    app.component(cpn.name, cpn);
  }
}
